name: docs

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [master]
  # 手动触发部署
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: 16
          cache: yarn

      # 缓存 node_modules
#      - name: Cache dependencies
#        uses: actions/cache@v2
#        id: yarn-cache
#        with:
#          path: |
#            **/node_modules
#          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-yarn-



#      # 如果缓存没有命中，安装依赖
#      - name: Install dependencies
##        if: steps.yarn-cache.outputs.cache-hit != 'true'
#        run: yarn install

#      # 清空缓存
#      - name: Clean dependencies
#        #        if: steps.yarn-cache.outputs.cache-hit != 'true'
#        run: yarn vite-clean-serve

      - name: 安装依赖
        run: yarn install

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: yarn docs:build

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 这是文档部署到的分支名称
          branch: gh-pages
          folder: test/.vuepress/dist